# Generated by Django 5.2.2 on 2025-06-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growattcredential',
            name='created_at',
        ),
    ]
