# Generated by Django 5.2.2 on 2025-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_power', models.FloatField(blank=True, null=True)),
                ('today_energy', models.FloatField(blank=True, null=True)),
                ('month_energy', models.FloatField(blank=True, null=True)),
                ('total_energy', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
